//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartHouse.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class AirConditioningSettings
    {
        public int Id { get; set; }

        [DisplayName("Air conditioning ON/OFF")]
        public bool AirConditioningOn { get; set; }

        [DisplayName("Wanted temperature (Celsius degrees)")]
        public float WantedTemperature { get; set; }

        [DisplayName("Mode")]
        public int AirConditioningMode { get; set; }
    }
}
