//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartHouse.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Setting
    {
        public int Id { get; set; }
        public bool CriticalTemperatureAlertYN { get; set; }
        public decimal CriticalTemperatureAlertValue { get; set; }
        public bool CriticalHumidityAlertYN { get; set; }
        public decimal CriticalHumidityAlertValue { get; set; }
        public bool MotionDetectionAlertYN { get; set; }
        public bool SoundDetectionAlertYN { get; set; }
        public bool CriticalGasAlertYN { get; set; }
        public decimal CriticalGasAlertValue { get; set; }
        public System.DateTime InternalTime { get; set; }
    }
}
