//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartHouse.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Setting
    {
        public int Id { get; set; }

        [Display(Name = "Alert critical temperature")]
        public bool CriticalTemperatureAlertYN { get; set; }

        [Display(Name = "Critical temperature (Celsius degrees)")]
        public decimal CriticalTemperatureAlertValue { get; set; }

        [Display(Name = "Alert critical humidity")]
        public bool CriticalHumidityAlertYN { get; set; }

        [Display(Name = "Critical humidity (%)")]
        public decimal CriticalHumidityAlertValue { get; set; }

        [Display(Name = "Alert motion detection")]
        public bool MotionDetectionAlertYN { get; set; }

        [Display(Name = "Alert sound detection")]
        public bool SoundDetectionAlertYN { get; set; }

        [Display(Name = "Alert gas detection")]
        public bool CriticalGasAlertYN { get; set; }

        [Display(Name = "Last updated")]
        public System.DateTime InternalTime { get; set; }
    }
}
