//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartHouse.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Settings
    {
        public int Id { get; set; }
        [Display(Name = "Alert critical temperature")]
        public bool CriticalTemperatureAlertYN { get; set; }

        [Display(Name = "Critical temperature (Celsius degrees)")]
        public decimal CriticalTemperatureAlertValue { get; set; }

        [Display(Name = "Alert critical humidity")]
        public bool CriticalHumidityAlertYN { get; set; }

        [Display(Name = "Critical humidity (%)")]
        public decimal CriticalHumidityAlertValue { get; set; }

        [Display(Name = "Alert motion detection")]
        public bool MotionDetectionAlertYN { get; set; }

        [Display(Name = "Alert sound detection")]
        public bool SoundDetectionAlertYN { get; set; }

        [Display(Name = "Alert gas detection")]
        public bool CriticalGasAlertYN { get; set; }

        [Display(Name = "Last updated")]
        public System.DateTime InternalTime { get; set; }

        [Display(Name = "Delete temperature & humidity historical data older than ")]
        public int DeleteTemperatureHumidityHistoricalDataOlderThan { get; set; }
        public int DeleteTemperatureHumidityHistoricalDataOlderThanUnitMeasure { get; set; }

        [Display(Name = "Delete motion detection historical data older than ")]
        public int DeleteMotionDetectionHistoricalDataOlderThan { get; set; }
        public int DeleteMotionDetectionHistoricalDataOlderThanUnitMeasure { get; set; }

        [Display(Name = "Delete sound detection historical data older than ")]
        public int DeleteSoundDetectionHistoricalDataOlderThan { get; set; }
        public int DeleteSoundDetectionHistoricalDataOlderThanUnitMeasure { get; set; }

        [Display(Name = "Delete gas detection historical data older than ")]
        public int CriticalGasHistoricalDataOlderThan { get; set; }
        public int CriticalGasHistoricalDataOlderThanUnitMeasure { get; set; }

        [Display(Name = "Email address for alerts")]
        public string AlertsToEmail { get; set; }

        [Display(Name = "Motion detection email alert interval")]
        public int SendMotionDetectionEmailAlertInterval { get; set; }
        public int SendMotionDetectionEmailAlertIntervalUnitMeasure { get; set; }

        [Display(Name = "Critical temperature interval")]
        public decimal CriticalTemperatureAlertMinValue { get; set; }
        public decimal CriticalTemperatureAlertMaxValue { get; set; }

        [Display(Name = "Critical humidity interval")]
        public decimal CriticalHumidityAlertMinValue { get; set; }
        public decimal CriticalHumidityAlertMaxValue { get; set; }
    }
}
