//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartHouse.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SmartHouse.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DROP EVENT `deleteMotionDetectionHistoryData`; CREATE DEFINER=`root`@`localhost` EVENT `deleteMotionDetectionHistoryData` ON SCHEDULE EVERY 1 MINUTE STARTS &apos;2018-02-18 18:34:28&apos; ON COMPLETION PRESERVE ENABLE DO delete from MotionDetectionData where TIMESTAMPDIFF({0}, InternalTime, now()) &gt;= {1}.
        /// </summary>
        public static string jobDeleteMotionDetectionHistoryData {
            get {
                return ResourceManager.GetString("jobDeleteMotionDetectionHistoryData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DROP EVENT `deleteSoundDetectionHistoryData`; CREATE DEFINER=`root`@`localhost` EVENT `deleteSoundDetectionHistoryData` ON SCHEDULE EVERY 1 MINUTE STARTS &apos;2018-02-18 18:34:28&apos; ON COMPLETION PRESERVE ENABLE DO delete from SoundDetectionData where TIMESTAMPDIFF({0}, InternalTime, now()) &gt;= {1}.
        /// </summary>
        public static string jobDeleteSoundDetectionHistoryData {
            get {
                return ResourceManager.GetString("jobDeleteSoundDetectionHistoryData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DROP EVENT `deleteTemperatureHumidityHistoryData`; CREATE DEFINER=`root`@`localhost` EVENT `deleteTemperatureHumidityHistoryData` ON SCHEDULE EVERY 1 MINUTE STARTS &apos;2018-02-18 18:34:28&apos; ON COMPLETION PRESERVE ENABLE DO delete from TemperatureHumidityData where TIMESTAMPDIFF({0}, InternalTime, now()) &gt;= {1}.
        /// </summary>
        public static string jobDeleteTemperatureHumidityHistoryData {
            get {
                return ResourceManager.GetString("jobDeleteTemperatureHumidityHistoryData", resourceCulture);
            }
        }
    }
}
